name: Environment Setup
description: Setup working environment
inputs:
  sync_args:
    description: Extra Arguments to provide to `uv sync`
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml
    - name: Setup UV
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install uv=${{ env.UV_VERSION }}
        uv tool install ruff sphinx pytest-cov
        uv --version
        ruff --version
        pytest --version
    - name: Install Project Dependencies
      shell: bash
      run: uv sync --all-extras --no-install-project --frozen ${{ inputs.sync_args }}
