= Common Use Cases for Synthetic Trend Data Generation
:source-highlighter: coderay

The "SynTrend" utility is intended to be highly configurable to support a range of use cases.
Some use cases are intuitive to support while others require some creativity to provide the 
intended outcome. 

== Simple Use Cases

These use cases focus on situations you would be able to support the functionality with little complexity
based on the available project documentation.

=== Single-Value Generation

Using a simple project configuration, you can create a single value dataset of your choice. This allows
the project file to only implement the value type, its value configuration, and potentially an output target.

.String-Type Value to generate random string between 8 and 10 characters long
[cols="a,a",test_name="single_value_string"]
|===

| [source,yaml]
----
type: string
min_length: 8
max_length: 10
----
| [source,console]
----
$ syntrend generate single_value_string.yaml
"ezS3H0JdIV"
----
|===

.Integer-Type Value (to generate any number between 5 and 10)
[cols="a,a",test_name="single_value_integer"]
|===

| [source,yaml]
----
type: integer
min_offset: 5
max_offset: 10
----
| [source,console]
----
$ syntrend generate single_value_integer.yaml
6
----
|===

.Random Value selection
[cols="a,a",test_name="random_choice"]
|===
| [source,yaml]
----
type: choice
items:
  - red
  - yellow
  - blue
  - orange
  - green
  - purple
----
| [source,console]
----
$ syntrend generate random_color.yaml
"blue"
----
|===

.Object-Type Value with properties containing their own definitions
[cols="a,a", test_name="single_value_object"]
|===

| [source,yaml]
----
type: object
properties:
  field_1:
    type: string
  field_2:
    type: integer
  field_3:
    type: float
  field_4:
    type: choice
    items:
      - small
      - medium
      - large
----
| [source,console]
----
$ syntrend generate single_value_object.yaml
{"field_1": "9d3bl12", "field_2": -95, "field_3": 125.221053, "field_4": "large"}
----

|===

Running any of these projects uses the `generate` command. Follow the documentation on how to change any number of parameters, including:

- how the generated objects will behave,
- where the will get written, and
- how many will get generated

=== Sequences of Records

Allowing any object to become a sequence is achieved through the
`output` property on the Object Definition, and allows you to define
how many records should be generated.

.Creating a sequence of 5 randomly generated strings
[cols="a,a",test_name="multi_value_string"]
|===

| [source,yaml]
----
type: string
output:
  count: 5
----
| [source,console]
----
$ syntrend generate multi_value_string.yaml
"tw3o094m8CFdaKYtE"
"7v6nkAUeFhH0T"
"EIdNLEA"
"FXrf9L31BcbE1YGsTK"
"ZbaY7IjAtdfMHLICI9L"
----

|===

=== Constants Across Records

Some cases require a dataset where a value must be consistent across the dataset. This ensures a level of consistency where multiple values/records should contain the same value.

This is achieved through the `static` property type, though an alternative method also exists using the expression look-back method below

[mermaid]
.....
---
config:
  themeVariables:
    xyChart:
      plotColorPalette: "#00F"
---
xychart-beta
    x-axis "Record Counts" 1 --> 10
    line [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
.....

Using this in a project could look like this:

.Object Sequence with static value
[cols="a,a", test_name="static_ref_events"]
|===
| [source,yaml]
----
output:
    count: 5
type: object
properties:
  timestamp:
    type: timestamp
    expression: this(1).timestamp \| default(new) + 5
  user_id:
    type: static
    value: jdoe
  value:
    type: integer
----
| [source, console]
----
$ syntrend generate project_config.yaml
{"timestamp": 1721376678, "user_id": "jdoe", "value": 101}
{"timestamp": 1721376683, "user_id": "jdoe", "value": -241}
{"timestamp": 1721376688, "user_id": "jdoe", "value": -367}
{"timestamp": 1721376693, "user_id": "jdoe", "value": 307}
{"timestamp": 1721376698, "user_id": "jdoe", "value": 300}
----

|===

Alternatively, it's also possible to have `syntrend` generate a random starting value and re-use it like a static value. The only different is instead of using the `static` type and `value` property, use the type of choice and set `expression` to copy the last value.

.Object Sequence with Randomly-generated static value
[cols="a,a", test_name="static_ref_random_start"]
|===
| [source, yaml]
----
output:
    count: 5
type: object
properties:
  timestamp:
    type: timestamp
    expression: this(1).timestamp \| default(new) + 5
  user_id:
    type: string
    min_length: 3
    max_length: 6
    expression: this(1).user_id \| default(new)
  value:
    type: integer

----

| [source, console]
----
$ syntrend generate random_start_static_seq.yaml
{"timestamp": 1721455177, "user_id": "mdt", "value": -222}
{"timestamp": 1721455182, "user_id": "mdt", "value": -136}
{"timestamp": 1721455187, "user_id": "mdt", "value": 262}
{"timestamp": 1721455192, "user_id": "mdt", "value": 364}
{"timestamp": 1721455197, "user_id": "mdt", "value": -231}
----

|===

=== String Formatting

Using the `expression` flag allows for the use of any https://jinja.palletsprojects.com/en/3.1.x/[Jinja Template] expression to

.Formatting Strings over a sequence
[cols="a,a",test_name="seq_format_string"]
|===
| [source,yaml]
----
output:
  count: 5
type: string
expression: new[:5] + "-test"
----
| [source,console]
----
$ syntrend generate seq_format_string.yaml
"8hmbP-test"
"gKOw0-test"
"hTL3i-test"
"jyBOq-test"
"rKHpC-test"
----

|===

=== Conditional Logic

It's possible to implement conditional logic to allow for static values that change within the dataset.

.Status Value changes on condition of another property
[cols="a,a",test_name="cond_status_change"]
|===
| [source,yaml]
----
output:
  count: 5
type: object
properties:
  ref:
    type: static
    value: status
  status:
    type: string
    expression: '"above" if this().sensor > 5 else "below"'
  sensor:
    type: integer
    expression: this(1).sensor + 2
    start: 0
----
| [source,console]
----
$ syntrend generate cond_status_change.yaml
{}
{}
----
|===

=== Numerical Trends

Creating numerical trends/patterns in your projects are provided through the use of the `expression` property.

IMPORTANT: Unlike charting applications, if