name: Create and Publish Package and Container Image

on:
  push:
    branches: ['feat/*', 'fix/*', 'release/*', 'main']

env:
  GH_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  UV_VERSION: 0.4.5
  PYTHON_BUILD_VER: "3.11"
  DEV_HOME: /opt/syntrend/dev
  BUILD_HOME: /opt/syntrend/build
defaults:
  run:
    shell: bash
jobs:
  build-prerelease:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Project
        uses: ./.github/actions/env_setup
        with:
          sync_args: --no-dev
      - name: Build Wheel
        run: uv build
      - name: Build Docker
        run: docker build -f Containerfile -t syntrend:${{ github.sha }} --build-arg SYNTREND_VERSION=$(grep "^version = " pyproject.toml | tr '"' "\n" | tail -n 2 | head -n 1) .
      - name: Export Docker
        run: docker save syntrend:$GITHUB_SHA | gzip > dist/syntrend-container.${{ github.sha }}.tar.gz
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        id: new_release
        with:
          path: ./dist
          key: release-${{ github.sha }}
  create-release:
    needs:
      - build-prerelease
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        id: new_release
        with:
          path: ./dist
          key: release-${{ github.sha }}
      - name: Create Release
        run: >
          gh release create --draft --repo ${{ github.repository }}
          ${{ github.ref_name }} dist/syntrend-*
        env:
          GH_TOKEN: ${{ github.token }}
