name: Test Syntrend

env:
  GH_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  UV_VERSION: 0.4.5
defaults:
  run:
    shell: bash
on:
  push:
    branches:
      - main
      - release/*
      - "feat/*"
      - "fix/*"
      - "chore/*"

jobs:
  tests:
    name: Run Test Suite
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Project
        uses: ./.github/actions/env_setup
        with:
          sync_args: --no-dev
      - name: Run Format Check
        run: uv run poe format-test
      - name: Run Linter Check
        run: poe lint-test --output-format=github
      - name: Run Test Suite
        run: poe test-report
      - name: Upload Test Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest results
          path: pytest-report.xml
          retention-days: 15
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage results
          path: coverage.xml
          retention-days: 15
